services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always